#!/bin/sh

is_ok() {
    local pid=$(pidof anyfi-controller)

    # There is no controller
    [ -z "$pid" ] && return 1

    # Unresponsive anyfi-console
    anyfi-console & sleep 1 ; kill $! && return 1

    return 0
}

monitor() {

    trap "exit 0" TERM

    while true; do
        if ! is_ok; then
            /etc/init.d/anyfi-controller restart
        fi
        # Sleep but awake immediately if there's a signal
        sleep 10 &
        wait
    done
    
    # Not reached
    exit 1
}

# Daemonize
cd /tmp
exec 0<&- 1>&- 2>&-
monitor &

exit 0
